### ISSUE TITLE
mentions do not work anymore

### ISSUE THREAD

**Issue by AlyxFoxy** [Varien-1936/Jeanne-Bot#14]
tried hug, kiss and pat but me and other person dont get mentioned

**Comment by Varien-1936** [comment]
I am aware of that, including the maintainer of Nextcord. It will be sorted by them

**Comment by Varien-1936** [comment]
So I tried out the commands again. This is the result:

On mobile:
![image](https://media.discordapp.net/attachments/913051824095916145/957218737126256641/Screenshot_20220326-120514_Discord-Beta.jpg)

On PC:
![image](https://media.discordapp.net/attachments/417800351530483712/957216326735265802/unknown.png)

The images show that on mobile, the author gets pings, including the target member but on PC, only the target member is pinged. To combat this, the author will no longer be mentioned except the target member. They will show up as name and discriminator.

**Comment by Varien-1936** [comment]
Authors are no longer mentioned except target members
